version: "3"

services:
  api:
    image: baz
    container_name: baz
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
