language: node_js
node_js: node
cache: npm

install:
  - npm ci

script:
  - npm test
  - npm run build

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  app:
    master: heroku-baz-prod
    develop: heroku-baz
  on:
    repo: AntonGluschuk/heroku-baz
  skip_cleanup: "true"
