name: Node.js CI

on:
  push:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-deps-
      - name: Install dependencies
      - run: npm ci
      - name: Run tests
      - run: npm test
      - name: Build
      - run: npm run build --if-present
      - name: Deploy on heroku
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY2}}
          heroku_app_name: "heroku-baz"
          heroku_email: "antongluschuk11@gmail.com"
        env:
          CI: true
